medecin_medecin:
    resource: "@MedecinBundle/Controller/MedecinController.php"
    type:     annotation

pharmacie:
    resource: "@PharmacieBundle/Controller/"
    type:     annotation
    prefix:   /

laboratoire:
    resource: "@LaboratoireBundle/Controller/"
    type:     annotation
    prefix:   /

hopitale:
    resource: "@HopitaleBundle/Controller/"
    type:     annotation
    prefix:   /

medecin:
    resource: "@MedecinBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#adesigns_calendar:
#  resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"
ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"
#ancarebeca_full_calendar_load:
#    path:     /full-calendar/load
#    defaults:
#        _controller: FullCalendarBundle:Calendar:load


fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"